version: '3'

networks:
  default:
    name: gco

services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/conf/nginx/empty.conf:/etc/nginx/conf.d/default.conf
      - ./docker/conf/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./docker/conf/hosts:/etc/hosts
      - ./:/var/www/html/
    container_name: gco_nginx
    links:
      - php
  php:
    build: ./docker/dockerfiles/php8
    expose:
      - 9003
    ports:
        - "8000:8000"
    environment:
      - XDEBUG_CONFIG=remote_host=172.17.0.1
      - PHP_IDE_CONFIG=serverName=cnpj
    volumes:
      - ./:/var/www/html/
      - ./docker/conf/hosts:/etc/hosts
    container_name: gco_php

  mysql:
    image: mysql:5.6
    container_name: gco_mysql
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=gco
      - MYSQL_DATABASE=gco
      - MYSQL_USER=gco
      - MYSQL_PASSWORD=gco